# Generated by Django 3.0.4 on 2020-04-04 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('fecha_registro', models.DateField()),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=5)),
                ('numero_entradas', models.IntegerField()),
                ('max_entradas_user', models.IntegerField()),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeketapp.Usuario')),
            ],
        ),
    ]
