# Generated by Django 3.0.4 on 2020-04-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='url_id',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
