# Generated by Django 3.0.4 on 2020-04-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0002_evento_url_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('qr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeketapp.Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeketapp.Usuario')),
            ],
        ),
    ]
