# Generated by Django 3.0.4 on 2020-04-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0003_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='key',
        ),
        migrations.AddField(
            model_name='evento',
            name='key',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
