# Generated by Django 3.0.4 on 2020-04-06 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0004_auto_20200406_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
