# Generated by Django 3.0.4 on 2020-04-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0005_auto_20200406_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='asistentes',
            field=models.ManyToManyField(to='freeketapp.Usuario'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeketapp.Organizador'),
        ),
    ]
