# Generated by Django 3.0.4 on 2020-04-06 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0006_auto_20200406_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='qr_id',
        ),
        migrations.AddField(
            model_name='entrada',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
