# Generated by Django 3.0.4 on 2020-04-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0009_auto_20200406_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ciudad',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evento',
            name='cpostal',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='direccion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
