# Generated by Django 3.0.4 on 2020-04-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0011_auto_20200411_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
