# Generated by Django 3.0.4 on 2020-04-18 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0014_confirmationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='date_adquisicion',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='numero_entradas',
        ),
        migrations.AddField(
            model_name='entrada',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.date(2020, 4, 18)),
        ),
        migrations.AddField(
            model_name='evento',
            name='numero_entradas_actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='evento',
            name='numero_entradas_inicial',
            field=models.IntegerField(default=1),
        ),
    ]
