# Generated by Django 3.0.4 on 2020-04-24 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0016_auto_20200419_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2020, 4, 24)),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.date(2020, 4, 24)),
        ),
    ]
