# Generated by Django 3.0.4 on 2020-04-27 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0017_auto_20200424_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.date(2020, 4, 27)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2020, 4, 27)),
        ),
    ]
