# Generated by Django 3.0.4 on 2020-05-08 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0018_auto_20200427_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='exclusive_org',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.date(2020, 5, 8)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2020, 5, 8)),
        ),
    ]
