# Generated by Django 3.0.4 on 2020-06-08 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0020_auto_20200509_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='img',
            field=models.ImageField(default='', upload_to='m'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.date(2020, 6, 8)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2020, 6, 8)),
        ),
    ]
