# Generated by Django 3.0.4 on 2020-06-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0022_auto_20200608_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='img',
            field=models.ImageField(blank=True, upload_to='m'),
        ),
    ]
