# Generated by Django 3.0.4 on 2020-06-09 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0024_evento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.date(2020, 6, 9)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2020, 6, 9)),
        ),
    ]
