# Generated by Django 3.0.4 on 2020-06-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0027_auto_20200614_1215'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listaespera',
            managers=[
            ],
        ),
    ]
