# Generated by Django 3.0.4 on 2020-06-15 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeketapp', '0028_auto_20200614_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organizador',
            name='cpostal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='organizador',
            name='telefono',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='fecha_adquisicion',
            field=models.DateField(default=datetime.date(2020, 6, 15)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2020, 6, 15)),
        ),
    ]
